name: "CD Pipeline"

on:
  workflow_run:
    workflows: ["Sample React CI Pipeline / Workflow"]
    types:
      - completed
  workflow_dispatch:

jobs:
  deploy: 
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: "Setup nodejs"
        uses: actions/setup-node@v4
        with:
          node-version: '21'

      - name: "Setup vercel cli"
        run: npm install -g vercel

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: ./build/

      - name: List artifacts
        run: |
          curl -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \https://api.github.com/repos/DeepikaReddy0503/React-Ci-Cd-setup/actions/runs/$GITHUB_RUN_ID/artifacts
     
      - name: "Download build files"
        uses: actions/download-artifact@v4
        with:
         name: build
         run-id: ${{ github.event.workflow_rund.id }}
         github-token: ${{ github.token }}

      - name: "Deploy to vercel"
        run: vercel --prod --token=${{ secrets.VERCEL_TOKEN }} --confirm --name=cicdproject